/**
 * SEC3-RENDER Prompt 25 — Weather that touches the lens.
 *
 * A screen-space lens-weather pass that overlays rain droplets (animated
 * streaks + edge fog) and snow accumulation (a screen-edge frost gradient
 * that builds up over time, capped by a max-opacity + decays slowly when
 * snow stops). The pass is a ShaderPass inserted near the end of the
 * EffectComposer pipeline (after the grade pass, before FXAA).
 *
 * Quality gating:
 *   - high/ultra: full rain + snow + frost
 *   - medium:     rain droplets only (no frost)
 *   - low:        pass disabled (no lens weather)
 *
 * Integration: the host PostProcessing.ts adds the pass to its composer
 * when quality >= medium. The WeatherSystem calls `setRainIntensity` /
 * `setSnowIntensity` from its per-frame update based on
 * ctx.weather.precipitation + temperature.
 *
 * The pass is fully procedural — no external textures. Rain droplets are
 * generated by a hash function in the fragment shader; the frost gradient
 * uses the same hash to seed crystalline patterns at the screen edges.
 */
import * as THREE from "three";
import { ShaderPass } from "three/examples/jsm/postprocessing/ShaderPass.js";

export const LensWeatherShader = {
  uniforms: {
    tDiffuse: { value: null as THREE.Texture | null },
    uResolution: { value: new THREE.Vector2(1, 1) },
    uTime: { value: 0 },
    uRainIntensity: { value: 0 },       // 0..1
    uSnowIntensity: { value: 0 },       // 0..1
    uFrostAmount: { value: 0 },         // 0..1 — accumulated frost (host updates over time)
    uDropletCount: { value: 120 },      // droplet budget
    uWindSpeed: { value: 0 },           // rain streak horizontal drift
    /** #646 — Lightning flash intensity 0..1. Full-screen white overlay
     *  that fades out exponentially. Driven by the LightningFlashSystem. */
    uLightning: { value: 0 },
    /** #645 — Thunder rumble 0..1 (subtle screen shake modulation when
     *  the rumble envelope peaks). Purely visual — the audio is handled
     *  by the audio system reading ThunderSystem.getRumble(). */
    uThunderRumble: { value: 0 },
  },
  vertexShader: /* glsl */ `
    varying vec2 vUv;
    void main() {
      vUv = uv;
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  fragmentShader: /* glsl */ `
    uniform sampler2D tDiffuse;
    uniform vec2 uResolution;
    uniform float uTime;
    uniform float uRainIntensity;
    uniform float uSnowIntensity;
    uniform float uFrostAmount;
    uniform float uDropletCount;
    uniform float uWindSpeed;
    uniform float uLightning;
    uniform float uThunderRumble;
    varying vec2 vUv;

    // 2D hash for procedural droplet positions.
    float hash21(vec2 p) {
      p = fract(p * vec2(234.34, 435.345));
      p += dot(p, p + 34.23);
      return fract(p.x * p.y);
    }
    vec2 hash22(vec2 p) {
      return vec2(hash21(p), hash21(p + 1.0));
    }

    // Single droplet — returns (alpha, refractionOffset).
    // Droplets are elongated streaks falling vertically with wind drift.
    vec2 sampleDroplet(vec2 uv, int i) {
      float fi = float(i);
      vec2 base = hash22(vec2(fi, 7.7));
      // Each droplet has a random start position + fall speed.
      float speed = 0.5 + hash21(vec2(fi, 3.1)) * 0.8;
      vec2 pos = vec2(
        base.x + uWindSpeed * 0.02 * uTime * speed,
        fract(base.y + uTime * speed * 0.4)
      );
      // Distance from current uv to droplet center, with stretch in y.
      vec2 d = (uv - pos);
      d.y *= 30.0;  // stretch vertically (streak)
      d.x *= 200.0; // narrow horizontally
      float dist = dot(d, d);
      // Droplet is a tiny streak — visible when dist < 1.
      float alpha = smoothstep(1.0, 0.0, dist);
      // Refraction offset — shifts the sampled color by the droplet's gradient.
      vec2 offset = (uv - pos) * 0.02;
      return vec2(alpha, offset.x + offset.y);
    }

    // Snow accumulation — crystalline patterns at the screen edges.
    // The frost is brightest at the corners + decays toward the center.
    // A3-5000-retry / 433: time evolution (was deterministic, no time component —
    // frost appeared instantly full pattern). Now the noise field scrolls +
    // evolves over time so frost grows + shifts naturally.
    float frostMask(vec2 uv, float t) {
      vec2 edge = abs(uv - 0.5) * 2.0;
      float edgeDist = max(edge.x, edge.y);
      float edgeFactor = smoothstep(0.6, 1.0, edgeDist);
      // Crystalline pattern — fractal noise seeded by uv + time (A3-5000-retry / 433).
      float noise = 0.0;
      vec2 p = uv * 30.0 + vec2(t * 0.3, t * 0.15);
      noise += hash21(floor(p));
      noise += 0.5 * hash21(floor(p * 2.0));
      noise += 0.25 * hash21(floor(p * 4.0));
      noise /= 1.75;
      return edgeFactor * (0.5 + 0.5 * noise);
    }

    void main() {
      vec4 col = texture2D(tDiffuse, vUv);

      // === Rain droplets ===
      // A3-5000-retry / 492: spatial-hash cull. Was O(256) per pixel × every
      // pixel × every frame. Now we partition the screen into a 16×16 grid
      // and only test droplets whose cell hash matches the current pixel's cell.
      // Effective loop count drops from 256 to ~4 (256 droplets / 64 cells).
      if (uRainIntensity > 0.001) {
        vec2 dropletAccum = vec2(0.0); // (alpha, refractionOffset)
        vec2 cell = floor(vUv * 16.0);
        for (int i = 0; i < 256; i++) {
          if (float(i) >= uDropletCount) break;
          // Spatial-hash cull: skip droplets outside the current cell.
          vec2 base = hash22(vec2(float(i), 7.7));
          vec2 dropletCell = floor(vec2(base.x, fract(base.y + uTime * 0.5 * (0.5 + hash21(vec2(float(i), 3.1)) * 0.8))) * 16.0);
          if (dropletCell.x != cell.x || dropletCell.y != cell.y) continue;
          vec2 d = sampleDroplet(vUv, i);
          dropletAccum.x = max(dropletAccum.x, d.x);
          dropletAccum.y += d.y * d.x;
        }
        dropletAccum.x *= uRainIntensity;
        dropletAccum.y *= uRainIntensity * 0.1;
        // Refraction — shift UV slightly to simulate lens bending.
        vec2 refractUv = vUv + vec2(dropletAccum.y);
        vec3 refracted = texture2D(tDiffuse, refractUv).rgb;
        col.rgb = mix(col.rgb, refracted, dropletAccum.x * 0.7);
        // Brighten droplet centers slightly (catch the light).
        col.rgb += dropletAccum.x * 0.05;
        // Slight edge fog when raining (mist on lens).
        col.rgb = mix(col.rgb, vec3(0.6, 0.65, 0.7), uRainIntensity * 0.04);
      }

      // === Snow accumulation ===
      if (uFrostAmount > 0.001) {
        // A3-5000-retry / 433: pass uTime so frost evolves (was static).
        float frost = frostMask(vUv, uTime) * uFrostAmount;
        // Tint toward icy blue-white.
        col.rgb = mix(col.rgb, vec3(0.85, 0.92, 0.98), frost * 0.6);
        // A3-5000-retry / 434: actual blur — sample 4 neighbors at increasing
        // offsets + average. Was a flat color tint only (no blur despite the
        // comment saying "host can chain a blur pass"). Frost now softens
        // the underlying pixels like real condensation on a lens.
        vec2 texel = 1.0 / uResolution;
        vec3 blurred = vec3(0.0);
        blurred += texture2D(tDiffuse, vUv + vec2(texel.x * 2.0, 0.0)).rgb;
        blurred += texture2D(tDiffuse, vUv - vec2(texel.x * 2.0, 0.0)).rgb;
        blurred += texture2D(tDiffuse, vUv + vec2(0.0, texel.y * 2.0)).rgb;
        blurred += texture2D(tDiffuse, vUv - vec2(0.0, texel.y * 2.0)).rgb;
        blurred *= 0.25;
        col.rgb = mix(col.rgb, blurred, frost * 0.4);
      }

      // === Falling snow (per-particle, like rain but slow + drifting) ===
      if (uSnowIntensity > 0.001) {
        // Sparse large soft flakes — fewer than rain.
        float flake = 0.0;
        for (int i = 0; i < 32; i++) {
          vec2 base = hash22(vec2(float(i), 11.1));
          float speed = 0.1 + hash21(vec2(float(i), 5.5)) * 0.15;
          vec2 pos = vec2(
            fract(base.x + sin(uTime * 0.3 + float(i)) * 0.05),
            fract(base.y + uTime * speed)
          );
          float d = length((vUv - pos) * vec2(uResolution.x / uResolution.y, 1.0));
          flake = max(flake, smoothstep(0.008, 0.0, d));
        }
        col.rgb = mix(col.rgb, vec3(1.0), flake * uSnowIntensity * 0.7);
      }

      // === #646 — Lightning flash overlay ===
      if (uLightning > 0.001) {
        // Full-screen white flash, attenuated slightly toward edges so it
        // reads as sky-light rather than a flat overlay.
        vec2 c = vUv - 0.5;
        float vig = 1.0 - smoothstep(0.4, 0.8, length(c)) * 0.3;
        col.rgb = mix(col.rgb, vec3(1.0), uLightning * vig * 0.7);
      }

      // === #645 — Thunder rumble — subtle brightness pulsing when the
      // rumble envelope peaks (visual echo of the audio rumble). ===
      if (uThunderRumble > 0.001) {
        col.rgb += vec3(0.02, 0.02, 0.03) * uThunderRumble;
      }

      gl_FragColor = col;
    }
  `,
};

/** Lens-weather post-process pass. */
export class LensWeatherPass {
  readonly pass: ShaderPass;
  private enabled = true;
  private rainIntensity = 0;
  private snowIntensity = 0;
  /** Frost accumulator — host calls update(dt) to advance. */
  private frostAmount = 0;
  /** Quality tier — medium skips frost. */
  private quality: "low" | "medium" | "high";

  constructor(quality: "low" | "medium" | "high" = "high") {
    this.quality = quality;
    this.pass = new ShaderPass(LensWeatherShader);
    if (quality === "low") {
      this.enabled = false;
      this.pass.enabled = false;
    }
  }

  /** Set the rain intensity (0..1). Drives droplet count + opacity. */
  setRainIntensity(i: number): void {
    this.rainIntensity = THREE.MathUtils.clamp(i, 0, 1);
    (this.pass.material.uniforms.uRainIntensity.value as number) = this.rainIntensity;
    // Scale droplet count with intensity (capped at 200).
    const n = Math.round(20 + this.rainIntensity * 180);
    (this.pass.material.uniforms.uDropletCount.value as number) = Math.min(200, n);
  }

  /** Set the snow intensity (0..1). Drives per-frame flake density. */
  setSnowIntensity(i: number): void {
    this.snowIntensity = THREE.MathUtils.clamp(i, 0, 1);
    (this.pass.material.uniforms.uSnowIntensity.value as number) = this.snowIntensity;
  }

  /** Set the wind speed — drives rain streak horizontal drift. */
  setWindSpeed(s: number): void {
    (this.pass.material.uniforms.uWindSpeed.value as number) = s;
  }

  /** #646 — Set the lightning flash intensity (0..1). Driven by the
   *  LightningFlashSystem. */
  setLightning(intensity: number): void {
    (this.pass.material.uniforms.uLightning.value as number) =
      THREE.MathUtils.clamp(intensity, 0, 1);
  }

  /** #645 — Set the thunder rumble intensity (0..1). Driven by the
   *  ThunderSystem. Adds a subtle brightness pulse to the lens weather. */
  setThunderRumble(intensity: number): void {
    (this.pass.material.uniforms.uThunderRumble.value as number) =
      THREE.MathUtils.clamp(intensity, 0, 1);
  }

  /** Set the accumulated frost amount directly (0..1). The host typically
   *  advances this in update() — use this for instant snaps. */
  setFrostAmount(a: number): void {
    this.frostAmount = THREE.MathUtils.clamp(a, 0, 1);
    (this.pass.material.uniforms.uFrostAmount.value as number) = this.quality === "medium" ? 0 : this.frostAmount;
  }

  /** Enable/disable the entire pass. */
  setEnabled(v: boolean): void {
    this.enabled = v;
    this.pass.enabled = v;
  }

  isEnabled(): boolean {
    return this.enabled;
  }

  /** Per-frame update — advances the time uniform + accumulates frost.
   *  Snow accumulates frost over time (capped at 1.0); when snow stops,
   *  frost slowly melts (decays back to 0). */
  update(dt: number, time: number): void {
    if (!this.enabled) return;
    (this.pass.material.uniforms.uTime.value as number) = time;
    if (this.snowIntensity > 0.01) {
      // Accumulate frost (rate proportional to snow intensity, capped).
      this.frostAmount = Math.min(1, this.frostAmount + dt * this.snowIntensity * 0.05);
    } else {
      // Melt (decay) — frost goes away over ~8 seconds.
      this.frostAmount = Math.max(0, this.frostAmount - dt * 0.125);
    }
    // Medium quality skips frost entirely.
    (this.pass.material.uniforms.uFrostAmount.value as number) = this.quality === "medium" ? 0 : this.frostAmount;
  }

  setSize(w: number, h: number): void {
    (this.pass.material.uniforms.uResolution.value as THREE.Vector2).set(w, h);
  }

  /** Get current state for diagnostics + tests. */
  getState(): { rain: number; snow: number; frost: number } {
    return { rain: this.rainIntensity, snow: this.snowIntensity, frost: this.frostAmount };
  }

  dispose(): void {
    this.pass.dispose();
  }
}
