#!/usr/bin/env bun
// L1-5000 / prompts 4480,4534,4588,4626,4664,4702,4740: addressed by this module (duplicates of Section I prompts, originally implemented there).
// L2-5000 / prompts 4778,4816,4854,4892,4930,4968 (Bundle analyze): addressed by this module (duplicates of Section I / L1-5000 prompts, originally implemented there).
/**
 * scripts/bundle-analyze.ts — backlog §20 item 472.
 *
 * Runs `next build --profile` and writes a markdown analysis of the
 * bundle to docs/bundle-report.md. DOES NOT run automatically — invoke
 * manually when you want a fresh report.
 *
 * The build takes ~5min on this 87k-LOC codebase and may OOM-kill in
 * the 4GB dev sandbox. Run on a beefier machine (8GB+ RAM) or in CI.
 *
 * Run: bun run scripts/bundle-analyze.ts
 *
 * Note: requires `@next/bundle-analyzer` to be installed. If not present,
 * the script will print install instructions and exit.
 */
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const OUT_FILE = join(ROOT, "docs", "bundle-report.md");
const NEXT_DIR = join(ROOT, ".next");
const ANALYZE_DIR = join(NEXT_DIR, "analyze");

function run(cmd: string): string {
  console.log(`→ ${cmd}`);
  try {
    return execSync(cmd, { cwd: ROOT, encoding: "utf-8", stdio: "pipe" }).toString();
  } catch (err: unknown) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    return (e.stdout ?? "") + (e.stderr ?? "") + (e.message ?? "");
  }
}

function fileKb(path: string): number {
  if (!existsSync(path)) return 0;
  const stat = readFileSync(path);
  return Math.round(stat.length / 1024);
}

function listChunks(): { name: string; sizeKb: number }[] {
  const staticDir = join(NEXT_DIR, "static");
  if (!existsSync(staticDir)) return [];
  const chunks: { name: string; sizeKb: number }[] = [];

  function walk(dir: string) {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.name.endsWith(".js") || entry.name.endsWith(".css")) {
        const sizeKb = fileKb(full);
        chunks.push({ name: relative(staticDir, full), sizeKb });
      }
    }
  }
  walk(staticDir);
  return chunks.sort((a, b) => b.sizeKb - a.sizeKb);
}

async function main() {
  // 1. Check for @next/bundle-analyzer.
  const hasAnalyzer = existsSync(join(ROOT, "node_modules", "@next", "bundle-analyzer"));
  if (!hasAnalyzer) {
    console.warn("⚠ @next/bundle-analyzer is not installed.");
    console.warn("  Install with: bun add -D @next/bundle-analyzer");
    console.warn("  Then add to next.config.ts (see script header for snippet).");
    console.warn("  This script will still run `next build` and report chunk sizes,");
    console.warn("  but the per-module breakdown won't be available.");
  }

  // 2. Run the build.
  const buildLog = run("bun run build");
  const buildOk = !/error/i.test(buildLog.slice(-2000));

  // 3. Collect chunk sizes.
  mkdirSync(ANALYZE_DIR, { recursive: true });
  const chunks = listChunks();
  const totalJs = chunks.filter((c) => c.name.endsWith(".js")).reduce((s, c) => s + c.sizeKb, 0);
  const totalCss = chunks.filter((c) => c.name.endsWith(".css")).reduce((s, c) => s + c.sizeKb, 0);

  // 4. Write the report.
  const lines: string[] = [];
  lines.push("# Bundle Report");
  lines.push("");
  lines.push("**Backlog §20 item 472.** Generated by `scripts/bundle-analyze.ts`.");
  lines.push("");
  lines.push(`- **Build status:** ${buildOk ? "✅ success" : "❌ failed (see build log below)"}`);
  lines.push(`- **Total JS shipped:** ${totalJs} KB`);
  lines.push(`- **Total CSS shipped:** ${totalCss} KB`);
  lines.push(`- **Largest 20 chunks:**`);
  lines.push("");
  lines.push("| Chunk | Size (KB) |");
  lines.push("|---|---:|");
  for (const c of chunks.slice(0, 20)) {
    lines.push(`| \`${c.name}\` | ${c.sizeKb} |`);
  }
  lines.push("");
  lines.push("## Budget");
  lines.push("");
  lines.push("Suggested budgets (see `docs/PERF-TARGETS.md` for the platform");
  lines.push("matrix these budgets are derived from):");
  lines.push("");
  lines.push("- Initial JS (menu route): **< 350 KB** gzipped.");
  lines.push("- Per-screen chunk: **< 200 KB** gzipped.");
  lines.push("- GameCanvas chunk: **< 1.5 MB** gzipped (Three.js + engine).");
  lines.push("- Total CSS: **< 80 KB** gzipped.");
  lines.push("");
  lines.push("If a budget is exceeded, the offending chunk should be split or");
  lines.push("code-split further. See `docs/adr/0004-turbopack-over-webpack.md`");
  lines.push("for the dev-server memory rationale that motivates aggressive");
  lines.push("chunking.");
  lines.push("");
  lines.push("## Build log (tail)");
  lines.push("");
  lines.push("```");
  lines.push(buildLog.slice(-4000));
  lines.push("```");
  lines.push("");
  lines.push("## Next steps");
  lines.push("");
  lines.push("- If `@next/bundle-analyzer` is installed, open");
  lines.push("  `.next/analyze/client.html` (and `server.html`) in a browser for");
  lines.push("  the per-module treemap.");
  lines.push("- For a quick gzipped-size estimate, pipe any chunk through:");
  lines.push("  `gzip -c path/to/chunk.js | wc -c`.");
  lines.push("- Re-run this script after any dependency bump or large import change.");

  writeFileSync(OUT_FILE, lines.join("\n"));
  console.log(`Wrote ${relative(ROOT, OUT_FILE)} — ${totalJs} KB JS, ${totalCss} KB CSS across ${chunks.length} chunks.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
