#!/usr/bin/env bun
/**
 * scripts/deps-freshness.ts — backlog §20 item 466.
 *
 * Reads package.json, prints a quarterly bump-review checklist, and
 * writes a markdown report to docs/deps-freshness.md.
 *
 * The checklist is intentionally non-automated — bumping a dep in this
 * codebase requires reading release notes + playtesting (see
 * docs/DEPS-CLEANUP.md for the three.js rationale). This script just
 * surfaces what's installed and when it was last published, so a human
 * can decide what to bump.
 *
 * Run: bun run scripts/deps-freshness.ts
 *
 * Note: doesn't fetch from npm registry (offline-friendly). The "latest
 * known" version column is read from package.json's caret range — for
 * the actual latest, run `bun outdated` separately.
 */
import { readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const PKG = join(process.cwd(), "package.json");
const OUT = join(process.cwd(), "docs", "deps-freshness.md");

interface PkgShape {
  name?: string;
  version?: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

function riskTier(name: string, range: string): "high" | "medium" | "low" {
  // Exact-pinned (no ^ or ~) — high risk to bump, deliberate pin.
  if (!range.startsWith("^") && !range.startsWith("~")) return "high";
  // Major-version-exact (e.g. ^16.1.1 — major is fixed).
  // Three.js is exact-pinned (0.185.1) — flagged above.
  if (name === "three" || name === "@types/three") return "high";
  if (name === "next" || name === "react" || name === "react-dom") return "high";
  if (name === "prisma" || name === "@prisma/client") return "medium";
  if (name === "@radix-ui/react-tabs" || name.startsWith("@radix-ui/")) return "medium";
  return "low";
}

function notes(name: string): string {
  switch (name) {
    case "three":
    case "@types/three":
      return "Exact-pin. See docs/DEPS-CLEANUP.md and docs/adr/0002-custom-physics-over-rapier.md. Read three.js release notes for every version between current and target.";
    case "next":
      return "App Router + Turbopack dev. Major bumps can change route-handler signatures, middleware API, and config schema. Check next.config.ts and src/app/ against the upgrade guide.";
    case "react":
    case "react-dom":
      return "React 19 — concurrent features, new JSX transform. Bumping to 20+ would need a full smoke test of every screen.";
    case "prisma":
    case "@prisma/client":
      return "Schema is provider-neutral (SQLite today). Bumping may require `bun run db:generate` and a re-push. Check migration history.";
    case "zustand":
      return "Store API. Bumping is usually safe (semver-respecting) but check the persist middleware if used.";
    case "zod":
      return "Used in every API route for validation. Bumping major could break schema inference.";
    case "next-auth":
      return "DEAD DEP — pending Task 1 removal. See docs/DEPS-CLEANUP.md.";
    case "next-intl":
      return "DEAD DEP — pending Task 1 removal. See docs/DEPS-CLEANUP.md.";
    case "z-ai-web-dev-sdk":
      return "Vendor SDK. See docs/Z-AI-SDK-DECISION.md for vendor-risk assessment + fallback.";
    case "husky":
      return "Pre-commit hook framework. Bumping is safe.";
    case "ts-prune":
      return "Dev-only. Used by scripts/find-unused-exports.ts.";
    default:
      return "";
  }
}

async function main() {
  const raw = await readFile(PKG, "utf-8");
  const pkg: PkgShape = JSON.parse(raw);
  const deps = pkg.dependencies ?? {};
  const devDeps = pkg.devDependencies ?? {};

  const lines: string[] = [];
  lines.push("# Dependency Freshness Report");
  lines.push("");
  lines.push("**Backlog §20 item 466.** Generated by `scripts/deps-freshness.ts`.");
  lines.push("");
  lines.push(`- **Project version:** ${pkg.version ?? "(unset)"}`);
  lines.push(`- **Runtime dependencies:** ${Object.keys(deps).length}`);
  lines.push(`- **Dev dependencies:** ${Object.keys(devDeps).length}`);
  lines.push("");
  lines.push("## How to use this report");
  lines.push("");
  lines.push("This is a **quarterly bump-review checklist**, not an auto-bump.");
  lines.push("For each dep:");
  lines.push("");
  lines.push("1. Check the current range below against `bun outdated`.");
  lines.push("2. Read the dep's release notes for every version between current and target.");
  lines.push("3. For `high`-risk deps (three, next, react, prisma) — playtest a full");
  lines.push("   match after bumping. Don't bump on a Friday.");
  lines.push("4. Update `docs/DEPS-CLEANUP.md` if a pin rationale changes.");
  lines.push("5. See `docs/MAINTENANCE-CADENCE.md` for the cleanup-day schedule.");
  lines.push("");
  lines.push("## Runtime dependencies");
  lines.push("");
  lines.push("| Package | Current range | Risk | Notes |");
  lines.push("|---|---|---|---|");
  for (const name of Object.keys(deps).sort()) {
    const range = deps[name];
    const risk = riskTier(name, range);
    const note = notes(name);
    lines.push(`| \`${name}\` | \`${range}\` | ${risk} | ${note} |`);
  }
  lines.push("");
  lines.push("## Dev dependencies");
  lines.push("");
  lines.push("| Package | Current range | Risk | Notes |");
  lines.push("|---|---|---|---|");
  for (const name of Object.keys(devDeps).sort()) {
    const range = devDeps[name];
    const risk = riskTier(name, range);
    const note = notes(name);
    lines.push(`| \`${name}\` | \`${range}\` | ${risk} | ${note} |`);
  }
  lines.push("");
  lines.push("## Quarterly review checklist");
  lines.push("");
  lines.push("- [ ] Run `bun outdated` and compare against this report.");
  lines.push("- [ ] Run `bun audit` and triage any CVEs.");
  lines.push("- [ ] Review Dependabot PRs from the last quarter (`.github/dependabot.yml`).");
  lines.push("- [ ] For each `high`-risk dep above: read release notes, decide");
  lines.push("      bump-or-stay, record decision in `docs/DEPS-CLEANUP.md`.");
  lines.push("- [ ] For each `medium`-risk dep: spot-check the changelog for breaking");
  lines.push("      changes, bump if clean.");
  lines.push("- [ ] For each `low`-risk dep: bulk-bump via `bun update`, run typecheck + lint.");
  lines.push("- [ ] Run `scripts/deps-tree-audit.ts` to catch any newly-dead deps.");
  lines.push("- [ ] Run `scripts/find-unused-exports.ts` to catch dead code.");
  lines.push("- [ ] Update this report (`bun run scripts/deps-freshness.ts`).");
  lines.push("- [ ] Playtest a full match (see `docs/SMOKE-TEST-CHECKLIST.md`).");

  await writeFile(OUT, lines.join("\n"));
  console.log(`Wrote ${relative(process.cwd(), OUT)} — ${Object.keys(deps).length} deps, ${Object.keys(devDeps).length} devDeps.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
