#!/usr/bin/env bun
/**
 * scripts/find-unused-exports.ts — backlog §20 item 489.
 *
 * Runs `bunx ts-prune` and parses the output into a markdown report
 * at docs/unused-exports-report.md.
 *
 * ts-prune statically analyzes the codebase for exported symbols that
 * are never imported anywhere. It's not perfect (dynamic imports +
 * reflection-based lookups produce false positives), but it's a good
 * starting point for cleanup-day dead-code removal.
 *
 * Run: bun run scripts/find-unused-exports.ts
 *
 * Output:
 *   docs/unused-exports-report.md  — full report (per-file + total)
 *   stdout                         — one-line summary
 *
 * Suppressing a false positive:
 *   Add a `// @ts-prune-resident` comment on the export line. ts-prune
 *   respects this and won't flag it.
 */
import { execSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const OUT_FILE = join(ROOT, "docs", "unused-exports-report.md");

interface UnusedExport {
  file: string;
  line: number;
  symbol: string;
}

function runTsPrune(): UnusedExport[] {
  // ts-prune output format (one per line):
  //   src/lib/game/foo.ts:42:  someExportedName
  //   src/lib/game/foo.ts:42:  someExportedName (used in module)
  // The "(used in module)" annotation means the symbol is used only
  // within its own file — the `export` keyword is redundant but the
  // symbol itself isn't dead. We keep these in the report but tag
  // them so the reader knows the difference.
  const raw = execSync("bunx ts-prune", {
    cwd: ROOT,
    encoding: "utf-8",
    stdio: ["pipe", "pipe", "pipe"],
    timeout: 180_000, // 3 min — large codebase
  }).toString();

  const out: UnusedExport[] = [];
  // Format: <file>:<line> - <symbol>[ (used in module)]
  const RE = /^(.+?):(\d+)\s+-\s+(.+?)(?:\s+\(used in module\))?$/;
  for (const line of raw.split("\n")) {
    const m = RE.exec(line.trim());
    if (!m) continue;
    const [, file, lineNum, symbol] = m;
    if (!file || !lineNum || !symbol) continue;
    if (file.includes("node_modules")) continue;
    if (file.includes(".test.")) continue;
    if (file.includes("__tests__")) continue;
    out.push({ file, line: Number(lineNum), symbol });
  }
  return out;
}

function groupByFile(items: UnusedExport[]): Map<string, UnusedExport[]> {
  const m = new Map<string, UnusedExport[]>();
  for (const it of items) {
    const arr = m.get(it.file) ?? [];
    arr.push(it);
    m.set(it.file, arr);
  }
  return m;
}

function main() {
  console.log("→ running bunx ts-prune (this can take a minute)…");
  const items = runTsPrune();
  const grouped = groupByFile(items);
  const total = items.length;
  const fileCount = grouped.size;

  const lines: string[] = [];
  lines.push("# Unused Exports Report");
  lines.push("");
  lines.push("**Backlog §20 item 489.** Generated by `scripts/find-unused-exports.ts`");
  lines.push("using `ts-prune`.");
  lines.push("");
  lines.push(`- **Total unused exports:** ${total}`);
  lines.push(`- **Files affected:** ${fileCount}`);
  lines.push("");
  lines.push("## How to use this report");
  lines.push("");
  lines.push("This is a starting point for cleanup-day dead-code removal");
  lines.push("(`docs/MAINTENANCE-CADENCE.md`). For each entry:");
  lines.push("");
  lines.push("1. Open the file at the line.");
  lines.push("2. Verify the export is truly unused — grep for the symbol");
  lines.push("   name across `src/`. ts-prune is static; dynamic imports");
  lines.push("   (`import(\"./foo\")`) or reflection-based lookups can");
  lines.push("   produce false positives.");
  lines.push("3. If truly unused, delete the export. Commit per-file.");
  lines.push("4. If used dynamically, suppress with a");
  lines.push("   `// @ts-prune-resident` comment on the export line.");
  lines.push("");
  lines.push("## Per-file breakdown");
  lines.push("");

  if (total === 0) {
    lines.push("_No unused exports found. Either the codebase is clean, or");
    lines.push("ts-prune failed to run (check the script output above)._");
  } else {
    for (const file of Array.from(grouped.keys()).sort()) {
      const entries = grouped.get(file)!.sort((a, b) => a.line - b.line);
      lines.push(`### \`${relative(ROOT, file) || file}\``);
      lines.push("");
      for (const e of entries) {
        lines.push(`- line ${e.line}: \`${e.symbol}\``);
      }
      lines.push("");
    }
  }

  lines.push("## Notes");
  lines.push("");
  lines.push("- ts-prune is static analysis. It will not detect:");
  lines.push("  - Dynamic imports: `import(\"./\" + name)`.");
  lines.push("  - Reflection: `obj[\"myExport\"]`.");
  lines.push("  - Re-exports through a barrel file (`index.ts`) that's");
  lines.push("    then dynamically imported.");
  lines.push("- Tests are excluded. An export used only by tests is");
  lines.push("  still flagged here — consider moving it to a");
  lines.push("  `_test_utils.ts` file so production code doesn't export it.");
  lines.push("- This report is a snapshot. Re-run after every cleanup");
  lines.push("  day; the count should trend down over time.");
  lines.push("");
  lines.push("## References");
  lines.push("");
  lines.push("- `docs/MAINTENANCE-CADENCE.md` — when to act on this report.");
  lines.push("- `docs/CODE-OWNERSHIP.md` — fragile files should be cleaned");
  lines.push("  carefully; don't delete an export from a god-file without");
  lines.push("  grepping for it twice.");
  lines.push("- ts-prune: https://github.com/nadeesha/ts-prune");

  writeFile(OUT_FILE, lines.join("\n"));
  console.log(
    `✓ Wrote ${relative(ROOT, OUT_FILE)} — ${total} unused exports across ${fileCount} files.`,
  );
}

main();
