#!/usr/bin/env bun
/**
 * scripts/jsdoc-audit.ts — backlog §20 item 464.
 *
 * Greps src/lib/game/systems/ .ts files for exported functions and reports
 * which ones lack a JSDoc block immediately above them. Writes a markdown
 * report to docs/jsdoc-coverage-report.md.
 *
 * Approach: a regex pass over each file. For each `export function foo(`
 * or `export const foo = (` (and `export async function`), check whether
 * the line immediately above ends with the close-of-JSDoc-marker (star
 * followed by slash). Crude but sufficient — false positives only when
 * someone uses a non-JSDoc comment style, which is rare in this codebase.
 *
 * Run: bun run scripts/jsdoc-audit.ts
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const SYSTEMS_DIR = join(process.cwd(), "src", "lib", "game", "systems");
const OUT_FILE = join(process.cwd(), "docs", "jsdoc-coverage-report.md");

interface ExportEntry {
  name: string;
  kind: "function" | "const" | "async-function" | "class";
  hasJsdoc: boolean;
  file: string;
  line: number;
}

const RE_EXPORT = /^(export\s+)?(async\s+)?(function|class)\s+([A-Za-z_$][A-Za-z_$0-9]*)/;
const RE_EXPORT_CONST = /^(export\s+)?const\s+([A-Za-z_$][A-Za-z_$0-9]*)\s*=\s*(async\s*)?\(?[^=]*=>/;

async function auditFile(path: string): Promise<ExportEntry[]> {
  const src = await readFile(path, "utf-8");
  const lines = src.split("\n");
  const entries: ExportEntry[] = [];
  for (let i = 0; i < lines.length; i++) {
    const ln = lines[i];
    const mFn = RE_EXPORT.exec(ln);
    const mConst = RE_EXPORT_CONST.exec(ln);
    if (!mFn && !mConst) continue;
    // Only `export`-prefixed lines count.
    if (mFn && !mFn[1]) continue;
    if (mConst && !mConst[1]) continue;

    let name: string;
    let kind: ExportEntry["kind"];
    if (mFn) {
      name = mFn[4];
      kind = mFn[2] ? "async-function" : mFn[3] === "class" ? "class" : "function";
    } else {
      name = mConst![2];
      kind = "const";
    }

    // Look backwards for the nearest non-blank line.
    let j = i - 1;
    while (j >= 0 && lines[j].trim() === "") j--;
    const prev = j >= 0 ? lines[j].trim() : "";
    const hasJsdoc = prev.endsWith("*/");
    entries.push({ name, kind, hasJsdoc, file: path, line: i + 1 });
  }
  return entries;
}

async function main() {
  const files = (await readdir(SYSTEMS_DIR))
    .filter((f) => f.endsWith(".ts"))
    .sort();
  const perFile: Record<string, ExportEntry[]> = {};
  let total = 0;
  let documented = 0;
  for (const f of files) {
    const path = join(SYSTEMS_DIR, f);
    const entries = await auditFile(path);
    perFile[f] = entries;
    total += entries.length;
    documented += entries.filter((e) => e.hasJsdoc).length;
  }

  const pct = total === 0 ? 0 : Math.round((documented / total) * 100);

  const lines: string[] = [];
  lines.push("# JSDoc Coverage Report — `src/lib/game/systems/`");
  lines.push("");
  lines.push(`**Backlog §20 item 464.** Generated by \`scripts/jsdoc-audit.ts\`.`);
  lines.push("");
  lines.push(`- **Total exports audited:** ${total}`);
  lines.push(`- **Documented (JSDoc block above):** ${documented}`);
  lines.push(`- **Undocumented:** ${total - documented}`);
  lines.push(`- **Coverage:** ${pct}%`);
  lines.push("");
  lines.push("## Method");
  lines.push("");
  lines.push("For each `export function foo()` / `export const foo = () =>` /");
  lines.push("`export async function foo()` / `export class Foo` in");
  lines.push("`src/lib/game/systems/*.ts`, check whether the nearest non-blank");
  lines.push("line above ends with `*/` (the close of a JSDoc block). Crude but");
  lines.push("sufficient — false positives only when a non-JSDoc comment style is");
  lines.push("used (rare in this codebase).");
  lines.push("");
  lines.push("## Per-file breakdown");
  lines.push("");
  lines.push("| File | Exports | Documented | Undocumented |");
  lines.push("|---|---:|---:|---:|");
  for (const f of Object.keys(perFile).sort()) {
    const e = perFile[f];
    const d = e.filter((x) => x.hasJsdoc).length;
    lines.push(`| \`${f}\` | ${e.length} | ${d} | ${e.length - d} |`);
  }
  lines.push("");
  lines.push("## Undocumented exports (action list)");
  lines.push("");
  for (const f of Object.keys(perFile).sort()) {
    const missing = perFile[f].filter((e) => !e.hasJsdoc);
    if (missing.length === 0) continue;
    lines.push(`### \`${f}\``);
    lines.push("");
    for (const m of missing) {
      lines.push(`- \`${m.name}\` (${m.kind}) — line ${m.line}`);
    }
    lines.push("");
  }
  lines.push("## Notes");
  lines.push("");
  lines.push("- This audit is per-systems-folder only. `src/lib/game/audio/`,");
  lines.push("  `src/lib/game/uiux/`, `src/lib/game/platform/`, etc. are out of");
  lines.push("  scope for this report — re-run with a different `SYSTEMS_DIR` to");
  lines.push("  audit them.");
  lines.push("- Documented ≠ correct. A `/** foo */` one-liner counts as");
  lines.push("  documented even if it doesn't describe params / returns /");
  lines.push("  exceptions. The intent of this audit is to find the *zero*-JSDoc");
  lines.push("  exports, not to enforce JSDoc quality.");
  lines.push("- Don't bulk-add stub JSDoc just to move the number. Add real");
  lines.push("  documentation when you touch the function.");

  await writeFile(OUT_FILE, lines.join("\n"));
  console.log(`Wrote ${relative(process.cwd(), OUT_FILE)} — ${documented}/${total} (${pct}%) documented.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
